name: sklad
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^9.0.0
  url_launcher: ^6.3.1
  device_info_plus: ^11.2.1
  flutter_animate: ^4.5.2
  mask_text_input_formatter: ^2.9.0
  logger: ^2.5.0
  flutter_svg: ^2.0.17
  equatable: ^2.0.7
  shared_preferences: ^2.3.5
  dio: ^5.7.0
  get_it: ^8.0.3
  go_router: ^14.6.3
  keyboard_dismisser: ^3.0.0
  fl_chart: ^0.70.2
  json_annotation: ^4.9.0
  formz: ^0.8.0
  flutter_spinkit: ^5.2.1
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  syncfusion_flutter_pdfviewer: ^28.1.39
  intl: ^0.19.0
  flex_dropdown: ^0.2.0
  flutter_cached_pdfview: ^0.4.3
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  json_serializable: ^6.9.0
  rename: ^3.0.2

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/fonts/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
